# Generated by Django 4.2.10 on 2024-03-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_product_seller'),
    ]

    operations = [
    ]
